### PR TITLE
Update sync_boostr_data usage documentation

### PR DESCRIPTION
**Pull request by mashalifshin**
We missed some `README` updates for the way the boostr sync script accepts the API credentials, so just adding them now. 

Reviewer, please take a look over the sync script docs and make sure I haven't missed anything else.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/consvc-shepherd/blob/main/CONTRIBUTING.md).
- [-] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable).
- [x] [Documentation](https://github.com/mozilla-services/consvc-shepherd/tree/main/docs) has been updated (if applicable).
- [-] Functional and performance test coverage has been expanded and maintained (if applicable).

### CODE REVIEW

**Review by nanagb — COMMENTED** [review]
We should update .env.example

**Review by nanagb — APPROVED** [review]

**Comment by mashalifshin** [comment]
> We should update .env.example

you're so fast!! Yes you're absolutely right, but looks like Cyprien already took care of `.env.example`. See anything else missing?

**Comment by nanagb** [comment]
> > We should update .env.example
> 
> you're so fast!! Yes you're absolutely right, but looks like Cyprien already took care of `.env.example`. See anything else missing?

Yep he's on it! I was just about to delete the comment :D

**Comment by mashalifshin** [comment]
> > > We should update .env.example
> > 
> > 
> > you're so fast!! Yes you're absolutely right, but looks like Cyprien already took care of `.env.example`. See anything else missing?
> 
> Yep he's on it! I was just about to delete the comment :D Everything else looks good to me

Thank you!

**Pull request merged**
